version: '3.8'

services:
  # FastAPI サーバー
  api:
    build: .
    container_name: shift-agent-api
    command: ["uvicorn", "src.shift_agent.api.app:app", "--host", "0.0.0.0", "--port", "8081"]
    ports:
      - "8081:8081"
    environment:
      - JOB_STORAGE_TYPE=filesystem
      - JOB_STORAGE_DIR=/app/job_storage
      - SOLVER_TIMEOUT_SECONDS=300
    volumes:
      - ./job_storage:/app/job_storage
    networks:
      - n8n-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MCP SSE サーバー
  mcp:
    build: .
    container_name: shift-agent-mcp
    command: ["python", "mcp_server.py", "--transport", "sse", "--sse-host", "0.0.0.0", "--sse-port", "8084"]
    ports:
      - "8084:8084"
    environment:
      - SHIFT_AGENT_API_URL=http://api:8081
      - MCP_TRANSPORT=sse
    depends_on:
      - api
    networks:
      - n8n-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # n8n
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
    networks:
      - n8n-network
    depends_on:
      - api
      - mcp

networks:
  n8n-network:
    driver: bridge

volumes:
  n8n_data: