name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below to help us resolve the issue quickly.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      description: Please verify these items before submitting
      options:
        - label: I searched existing issues and didn't find a duplicate
          required: true
        - label: I tested with the latest version
          required: true
        - label: I checked the troubleshooting guide in CLAUDE.md
          required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "The API endpoint returns a 500 error when..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Start the server with `make run`
        2. Send POST request to `/api/shifts/solve-sync`
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: "The API should return a valid schedule response"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: "The API returns a 500 Internal Server Error"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of the system is affected?
      options:
        - API (FastAPI endpoints)
        - Solver (Timefold optimization)
        - MCP Server
        - Domain Models
        - Job Storage
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your development environment details
      placeholder: |
        - OS: macOS 14.0
        - Python: 3.11.5
        - Java: 17.0.1
        - Browser: Chrome 120 (if applicable)
        - Docker: Yes/No
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs/Screenshots
      description: Include relevant error messages, stack traces, or screenshots
      placeholder: "Paste error logs here or attach screenshots"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: "This started happening after..."
