name: 💡 Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-review"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide detailed information to help us understand your request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      description: Please verify these items before submitting
      options:
        - label: I searched existing issues and feature requests
          required: true
        - label: This feature doesn't exist in the current version
          required: true
        - label: I checked the roadmap and documentation
          required: false

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief, clear description of the feature
      placeholder: "Add support for overtime constraints in shift scheduling"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - API Endpoints
        - Scheduling Constraints
        - Solver Configuration
        - MCP Integration
        - User Interface
        - Documentation
        - Performance
        - Testing
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "Currently, the system cannot handle overtime rules, which are essential for compliance with labor laws..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: |
        1. Add overtime configuration to employee model
        2. Create new constraint for overtime limits
        3. Update API to accept overtime parameters
        4. Add overtime calculation to weekly analysis
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Case Example
      description: Provide a concrete example of how this feature would be used
      placeholder: |
        A hospital needs to ensure nurses don't work more than 60 hours per week,
        with overtime rates applied after 40 hours. The scheduler should:
        - Prioritize regular hours first
        - Apply overtime constraints
        - Calculate cost implications
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: "Instead of adding this to the core solver, it could be implemented as a post-processing step..."

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would significantly improve workflow
        - High - Blocking current use case
        - Critical - Required for production use
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Willingness
      description: Are you willing to help implement this feature?
      options:
        - label: I can help with design/requirements
        - label: I can contribute code
        - label: I can help with testing
        - label: I can help with documentation

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: "This feature is similar to what OptaPlanner offers in their examples..."
