# Docker Compose configuration is not used, changed to simple Dockerfile build
# To avoid this issue, we now specify the Dockerfile directly in devcontainer.json

# The original docker-compose.yml is not used but
# kept for production environment reference

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/workspace
    networks:
      - shift-network

networks:
  shift-network:
    driver: bridge