name: Infrastructure Deployment

on:
  push:
    branches: [main]
    paths:
      - 'infrastructure/**'
  pull_request:
    branches: [main]
    paths:
      - 'infrastructure/**'
  workflow_dispatch:
    inputs:
      stack:
        description: 'Pulumi stack to deploy (dev/prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
      action:
        description: 'Action to perform'
        required: true
        default: 'preview'
        type: choice
        options:
          - preview
          - up
          - destroy

jobs:
  infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install Pulumi CLI
        run: |
          curl -fsSL https://get.pulumi.com | sh
          echo "$HOME/.pulumi/bin" >> $GITHUB_PATH

      - name: Install Pulumi dependencies
        run: |
          uv sync --frozen --no-install-project

      - name: Configure Pulumi
        run: |
          pulumi version
          pulumi whoami
        working-directory: ./infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Initialize Pulumi Stack (PR)
        if: github.event_name == 'pull_request'
        run: |
          pulumi stack select dev --create
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Pulumi Preview (PR)
        if: github.event_name == 'pull_request'
        uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: dev
          work-dir: ./infrastructure
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Initialize Pulumi Stack (Manual Preview)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'preview'
        run: |
          pulumi stack select ${{ github.event.inputs.stack }} --create
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Pulumi Preview (Manual)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'preview'
        uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: ${{ github.event.inputs.stack }}
          work-dir: ./infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Initialize Pulumi Stack (Main Branch)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          pulumi stack select dev --create
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Pulumi Up (Main Branch)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: dev
          work-dir: ./infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Initialize Pulumi Stack (Manual Up)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'up'
        run: |
          pulumi stack select ${{ github.event.inputs.stack }} --create
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Pulumi Up (Manual)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'up'
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: ${{ github.event.inputs.stack }}
          work-dir: ./infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Pulumi Destroy (Manual)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        uses: pulumi/actions@v5
        with:
          command: destroy
          stack-name: ${{ github.event.inputs.stack }}
          work-dir: ./infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Export Stack Outputs
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'up')
        uses: pulumi/actions@v5
        with:
          command: stack output --json
          stack-name: ${{ github.event.inputs.stack || 'dev' }}
          work-dir: ./infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
